config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books
  resources :categories

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :avatar, styles: { thumb: "100x100>", medium: "200x200>" },  :default_url => "missing_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates :name, presence: true, length: {minimum: 1, maximum: 50}
  validates :authors, presence: true, length: {minimum: 3, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 450}

  has_many :book_categories
  has_many :categories, through: :book_categories

end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base
  belongs_to :book
  belongs_to :category  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :book_categories
  has_many :books, through: :book_categories

  validates :name, presence: true, length: {minimum:3,maximum:25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user! 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :update, :destroy,:edit]
  before_action :require_admin, except: [:index,:show]

  def index
    @books = Book.paginate(page: params[:page],per_page: 5)
  end

  def show

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "The book was successfuly created"
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @book.update(book_params)
      flash[:success] = "The book was successfuly edited"
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "The book was successfuly deleted"
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name,:description,:avatar,:authors, category_ids: [])
  end

  def require_admin
   if  !current_user.admin?
     redirect_to books_path
   end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show,:edit,:update,:destroy]
  before_action :require_admin, except: [:index,:show]

  def index
    @categories = Category.paginate(page: params[:page],per_page: 5)
  end

  def show
    @category_books = @category.books.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def edit

  end

  def create
     @category = Category.new(category_params)
     if @category.save
       flash[:success] = "The category was successfuly created"
       redirect_to categories_path
     else
       render 'new'
     end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "The category was successfuly edited"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "The category was successfuly deleted"
    redirect_to categories_path
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
       if  !current_user.admin?
         redirect_to categories_path
       end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name%>
      </div>
      <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "name of book", autofocus: true%>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :description%>
    </div>
      <div class="col-sm-8">
      <%= f.text_area :description,rows:8, class: "form-control", placeholder: "Small description about book"%>
    </div>
  </div>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :authors%>
    </div>
    <div class="col-sm-8">
    <%= f.text_field :authors, class: "form-control", placeholder: "Authors of this book"%>
  </div>
</div>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :avatar%>
    </div>
      <div class="col-sm-8">
      <%= f.file_field :avatar%>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <%end%>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit  class:"btn btn-primary btn-lg"%>
    </div>
  </div>
    <% end %>

   <div class="col-xs-5 col-xs-offset-5">
    [ <%= link_to "Back to all books", books_path %> ]
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1 align="center"> Edit chosen book </h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1 align="center"> All books: </h1>
<div align="center">
  <%= will_paginate %>
</div>
  <% @books.each do |book| %>
  <div class="row center">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="book-avatar">
          <%=  image_tag book.avatar.url(:thumb) %>
        </div>
        <div class="book-name">
          <%= link_to book.name, book_path(book) %>
        </div>
        <div class="description">
          <%= truncate(book.description , length: 100) %>
        </div>
        <div class="authors">
           <p >Author(s): <i><%=  book.authors %></i></p>
        </div>
        <% if book.categories.any? %>
          <p>Categories: <%= render book.categories %></p>
        <% end %>
          <div class="article-actions">
            <% if (user_signed_in? && current_user.admin?)  %>
          <%= link_to "Delete book",book_path(book), method: :delete,
                                        data: {confirm: "Are you sure?"} , class: "btn btn-xs btn-danger" %>
          <%= link_to "Edit book", edit_book_path(book), class: "btn btn-xs btn-primary" %>
          <% end %>
        </div>        
      </div>
    </div>
  </div>
  <% end %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/books/new.html.erb
<h1 align="center"> New book </h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h2 align="center">Name: <%= @book.name %><h2>
  <div class="well col-xs-8 col-xs-offset-2">
    <ul class="listing">
      <div class="row center">
        <div class=" col-md-4 col-md-offset-4">
          <li><%= image_tag @book.avatar.url(:medium)%></li>
          </div>
      </div>
    </ul>
    <h4 class="center"><strong> Description: </strong></h4>
    <hr>
    <p class="description"><%= @book.description%></p>
    <hr>
    <p class="authors">Author(s): <i><%= @book.authors%></i></p>
    <% if @book.categories.any? %>
    <p> <%= render @book.categories %> </p>
    <% end %>
    <div class="book-actions">
      <% if (user_signed_in? && current_user.admin?)  %>
        <%= link_to "Edit book", edit_book_path(@book), class: "btn btn-xs btn-success" %>
        <%= link_to "Delete book", book_path(@book), method: :delete,
                                      data: {confirm: "Are you sure?"} , class: "btn btn-xs btn-danger" %>
      <% end %>                                
        <%= link_to "View all books", books_path, class: "btn btn-xs btn-primary" %>

    </div>
  </div>

app/views/categories/_category.html.erb
<span class="badge" > <%= link_to category.name, category_path(category) %>  &nbsp; </span>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
  <div class="control-label col-sm-2">
    <%= f.label :name%>
  </div>
  <div class="col-sm-8">
  <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true%>
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit class:"btn btn-primary btn-lg"%>
</div>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center"> Edit chosen category: </h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">List All Categories</h1>
<div align="center">
  <% @categories.each do |category| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li class="book-title">
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
        <li><small><%= pluralize(category.books.count, "books") %></small></li>
      </div>
    </div>
  </ul>
  <%end%>

</div>

app/views/categories/new.html.erb
<h1 align="center"> New category: </h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"> <%= "Categories:" + @category.name%> </h1>
<div align="center">
  <div class="row">
      <% if (user_signed_in? && current_user.admin?)  %>
    <span class="badge" ><%= link_to "Edit this category", edit_category_path(@category) %></span>
      <% end  %>
    </div>
      <%= will_paginate @category_books %>
    <% @category.books.each do |book| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="book-avatar">
            <%=  image_tag book.avatar.url(:thumb) %>
          </div>
          <div class="book-name">
            <%= link_to book.name, book_path(book) %>
          </div>
          <div class="book-description">
            <%= truncate(book.description , length: 100) %>
          </div>
            <div class="article-actions">
                <% if (user_signed_in? && current_user.admin?)  %>
            <%= link_to "Delete book",book_path(book), method: :delete,
                                          data: {confirm: "Are you sure?"} , class: "btn btn-xs btn-danger" %>
            <%= link_to "Edit book", edit_book_path(book), class: "btn btn-xs btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div align="center">
        <%= will_paginate @category_books%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OnlineLibrary" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <%= link_to "Online Library", books_path, class: "navbar-brand", id: "logo"  %>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in?  %> 
            <li><%= link_to "All books", books_path  %></li>
            <% end %>
             <% if (user_signed_in? && current_user.admin?)  %>
            <li><%= link_to "New book", new_book_path  %></li>
            <% end %>
            <% if user_signed_in?  %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                 <li> <%= link_to "All Categories", categories_path %> </li>
                  <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %> </li>
                  <%end%>
                    <% if (user_signed_in? && current_user.admin?)  %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Create new category", new_category_path %></li>
                    <% end %>
                    <% end %>
                </ul>
            </li>
          </ul>
            <% if (user_signed_in? ) %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Log out", destroy_user_session_path , method: :delete %></li>
              </ul>
          <% end %>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/span-->
    </div><!--/row-->

      <footer>
        <p>&copy; Tyagelsky 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1> Welcome to Online Library  </h1>
<%= link_to "logout", destroy_user_session_path, method: :delete %>